### ISSUE TITLE
Can't Load Decks

### ISSUE THREAD

**Issue by HazelnutCookie** [UCProjects/UnderScript#17]
It worked fine for exactly one day, but now I can't load decks at all. I'm not sure if it's just my internet, or if something in the extension broke. Everything else is fine, so I would love to know if there is an easy fix.

**Comment by feildmaster** [comment]
What does it do? 

1. Do the decks not show at all?
1. Do the decks show, but it does nothing when you click on it?

**Comment by HazelnutCookie** [comment]
> What does it do?
> 
> 1. Do the decks not show at all?
> 2. Do the decks show, but it does nothing when you click on it?

They show fine, and I can save and interact with them, they just do nothing when I click to load them

**Comment by feildmaster** [comment]
Alright, what browser are you using? And are you able to open the console and copy any errors that may show?

**Comment by HazelnutCookie** [comment]
> Alright, what browser are you using? And are you able to open the console and copy any errors that may show?

I'm on google chrome. How do I open the console?

**Comment by HazelnutCookie** [comment]
DevTools failed to load source map: Could not load content for https://undercards.net/css/bootstrap.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
userscript.html?name=UnderCards%20script.user.js&id=6bbd786b-fb27-44c2-8b70-9e5059634ff3:11556 SimpleToast(v2.0): Loaded
userscript.html?name=UnderCards%20script.user.js&id=6bbd786b-fb27-44c2-8b70-9e5059634ff3:11559 SimpleToast(v2.0): Publicized
userscript.html?name=UnderCards%20script.user.js&id=6bbd786b-fb27-44c2-8b70-9e5059634ff3:19715 UnderScript(v0.45.1): Loaded
DevTools failed to load source map: Could not load content for https://undercards.net/js/tippy-bundle.iife.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for https://undercards.net/js/popper.min.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

Found the console, here's what popped up

**Comment by feildmaster** [comment]
Did you try loading a deck and seeing what pops up, if anything?

**Comment by HazelnutCookie** [comment]
> Did you try loading a deck and seeing what pops up, if anything?

Nothing new pops up

**Comment by HazelnutCookie** [comment]
> Did you try loading a deck and seeing what pops up, if anything?

Nothing new pops up

**Comment by feildmaster** [comment]
Should be fixed now, yes?
